name: Phonebook CI 

on: 
  push:
   branches:
    - main
  pull_request:
    branches:
     - main
     
jobs:

  test_code:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Run tests
        run: |
          python3 phonebook_test.py

      - name: Notify on slack on Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Sinatra
          SLACK_TITLE: Continuous Integration Report
          SLACK_MESSAGE: |
            Tests ${{ job.status }} in the latest commit
            Commit: ${{ github.sha }}
            Committer: ${{ github.actor }}
            Workflow Run URL: ${{ github.event.workflow_run.url }}
          SLACK_COLOR: ${{ job.status }}

      - name: Notify on Slack on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Sinatra
          SLACK_TITLE: Continuous Integration Report
          SLACK_MESSAGE: |
            Tests ${{ job.status }} in the latest commit
            Commit: ${{ github.sha }}
            Committer: ${{ github.actor }}
            Workflow Run URL: ${{ github.event.workflow_run.url }}
          SLACK_COLOR: ${{ job.status }}